dependencies {
    implementation(project(":modules:CTNH-Lib")){transitive = false}

    // Apotheosis
    modImplementation(ctnh.apotheosis)
    modImplementation(ctnh.attributelib)
    modImplementation(ctnh.placebo)

    // ars
    modImplementation(ctnh.geckolib)
    modImplementation(ctnh.arsnouveau)

    // botania
    modImplementation(ctnh.patchouli)
    modImplementation(ctnh.botania)
    modImplementation(ctnh.mythicbotany)
    modImplementation(ctnh.extrabotany)
    modImplementation(ctnh.eventwrapper)
    annotationProcessor(ctnh.libx)
    modImplementation(ctnh.libx)

    // Blood Magic
    modImplementation(ctnh.bloodmagic)

    // AE2
    modImplementation(ctnh.ae2)
    modImplementation(ctnh.guideme)
    
    modImplementation(ctnh.sophisticatedcore)
    modCompileOnly(variantOf(ctnh.curios) { classifier("api") })
    modImplementation(ctnh.twilightforest)
    modImplementation(ctnh.hostile)
    modImplementation(ctnh.lendercataclysm)
    modImplementation(ctnh.lionfishapi)
    modImplementation(ctnh.legendary)
    modImplementation(ctnh.avaritia)

    modLocalRuntime(ctnh.curios)
}
