dependencies {
    compileOnly("org.jetbrains:annotations:26.0.1")

    // Mixin
    annotationProcessor('org.spongepowered:mixin:0.8.5:processor')

    modImplementation(project(":modules:CTNH-Lib")){transitive = false}

    // JEI, EMI, Jade
    //modImplementation("curse.maven:jei-238222:7181650")
    //modCompileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    //modRuntimeOnly("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")
    //modRuntimeOnly("dev.emi:emi-forge:${emi_version}+${minecraft_version}")
    modImplementation("curse.maven:jade-324717:6855440")

    // GregTech and dependencies
    modImplementation("com.gregtechceu.gtceu:gtceu-${minecraft_version}:${gtceu_version}:slim") { transitive = false }
    modImplementation("com.lowdragmc.ldlib:ldlib-forge-${minecraft_version}:${ldlib_version}") { transitive = false }
    modImplementation("com.tterrag.registrate:Registrate:${registrate_version}")
    modImplementation("dev.toma.configuration:configuration-forge-${minecraft_version}:${configuration_version}")

    //Create
    modImplementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    modImplementation("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}")
    modImplementation("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}")


    modRuntimeOnly("curse.maven:modernfix-790626:6719008")

    // KubeJS
    modImplementation("dev.latvian.mods:kubejs-forge:${kubejs_version}")
    modImplementation("dev.latvian.mods:rhino-forge:${rhino_version}")
    modImplementation("dev.architectury:architectury-forge:${architectury_version}")

    // Apotheosis
    modImplementation("curse.maven:apotheosis-313970:6147871")
    modImplementation("curse.maven:attributelib-898963:5634071")
    modImplementation("curse.maven:placebo-283644:6274231")
    //sophisticated
    modImplementation("curse.maven:sophisticated-core-618298:7165739")
    //ars
    modImplementation("software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}")
    modImplementation("com.hollingsworth.ars_nouveau:ars_nouveau-${minecraft_version}:${arsnouveau_version}")

    //botania
    modImplementation("curse.maven:patchouli-306770:4966125")
    modImplementation("vazkii.botania:Botania:${botania_version}")
    modImplementation("curse.maven:mythicbotany-400058:5101899")
    modImplementation("curse.maven:extrabotany-reburn-1271869:6818025")
    modImplementation("curse.maven:event-wrapper-1256971:6788387")
    annotationProcessor "org.moddingx:LibX:${minecraft_version}-${libx_version}"
    modImplementation("org.moddingx:LibX:${minecraft_version}-${libx_version}")

    // Blood Magic
    modImplementation("curse.maven:blood-magic-224791:7253333")

    // Curios
    modRuntimeOnly("top.theillusivec4.curios:curios-forge:${curios_version}")
    modCompileOnly("top.theillusivec4.curios:curios-forge:${curios_version}:api")

    // Twilight forest
    modImplementation("curse.maven:twilight_forest-227639:5468648")

    //Hostile Neural NetWork
    modImplementation("curse.maven:hostile_neural_network-552574:5895036")


    modRuntimeOnly("curse.maven:just-enough-characters-250702:6680042")
    //legendary_survival
    modImplementation("curse.maven:legendary_survival_overhaul-840254:6750561")
}