org.gradle.jvmargs = -Xmx3G
org.gradle.parallel = true
org.gradle.caching = true

minecraft_version = 1.20.1
forge_version = 47.4.1
mapping_channel = parchment
mapping_version = 2023.09.03

# Mod Properties
mod_version = 0.65
maven_group = com.moguang.ctnhmana
archives_base_name = CTNH-Mana
mod_id = ctnhmana
mod_name = CTNH Mana
mod_url = https://github.com/CTNH-Team/CTNH-Mana
mod_author = CTNH Team
mod_description = Mod of the mana part for the modpack Create: New Horizon
mod_license = LGPLv3